blank_issues_enabled: false
contact_links:
    url: https://github.com/RakSrinaNa/TwitchMiner/discussions
    about: Got a more generic thing to say that isn't an issue or feature request / need support? Start a discussion here
