name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APP_JAVA_VERSION: 17

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - name: Set gradlew executable
        run: chmod +x ./gradlew
      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - name: Set gradlew executable
        run: chmod +x ./gradlew
      - name: Run tests
        uses: gradle/gradle-build-action@v2.0-beta.4
        with:
          arguments: test
      - name: Report test results
        uses: allegro-actions/junit-reporter@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          path: 'build/test-results/test/*.xml'
          show: 'all'
