name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APP_JAVA_VERSION: 17

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - name: Set gradlew executable
        run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - name: Set gradlew executable
        run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2.0-beta.4
        with:
          arguments: test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: build/test-results/*.xml
