name: "Qodana"

on:
  push:
  workflow_dispatch:

jobs:
  qodana:
    name: "Qodana"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: ~/work/_temp/_github_home/qodana-cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-
      - name: Run Qodana
        uses: JetBrains/qodana-action@v3.2.1
        with:
          linter: qodana-jvm-community
      - name: Save Qodana's results to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'qodana-report'
          path: ${{ github.workspace }}/qodana

  publish-qodana:
    name: "Qodana pages"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - qodana
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: 'qodana-report'
          path: quodana
      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: qodana/report
          destination_dir: ./