name: 'Test Report'

on:
  workflow_run:
    workflows: [ 'CI' ]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download test report artifact
        uses: actions/download-artifact@v2
        with:
          name: test-results
      - uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: '*.xml'
          reporter: java-junit
          fail-on-error: 'false'